version: "3.2"
services:
  easypush:
    build: .
    restart: on-failure
    networks:
      webserver:
        aliases:
          - easypush
    volumes:
      - /root/volumes/easypush:/app/prisma/data

networks:
  webserver:
    external: true