version: "3.2"
services:
  serve:
    image: node:14.3.0
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: nodemon dist/server/index.js
    env_file: .env
    environment:
      NODE_ENV: development