version: "3.2"
services:
  easypush:
    volumes:
      - type: volume
        source: staging-easypush
        target: /app/store/data
    ports:
      - target: 80
        published: 80
        protocol: tcp

volumes:
  staging-easypush:
